### ISSUE TITLE
Snap or flatpak support?

### ISSUE THREAD

**Issue by alfonsojon** [RPCS3/rpcs3-binaries-linux#1]
I'd really appreciate if Snap or Flatpak were a supported method of installation, as .AppImage files are difficult to integrate with just about any desktop environment without the use of third party software or making a launcher yourself.

**Comment by hcorion** [comment]
Using AppImages work better for us since they're more distro-independent and just work, rather than having to deal with the flatpak runtime. Anyways, please close this issue and don't open issues here since no one checks this issue tracker, the main issue tracker is at https://github.com/RPCS3/rpcs3.
We have a closed issue here https://github.com/RPCS3/rpcs3/issues/5935 regarding Flatpak support, and we have no intention to add a Flatpak build option right now.

**Comment by alfonsojon** [comment]
Got it, thanks!
